### ISSUE TITLE
simulator/core/atomic_support.h clang 3.4 bug, should we bother with it anymore?

### ISSUE THREAD

**Issue by gemarcano** [lab11/M-ulator#25]
I found the following [comment in atomic_support.h](https://github.com/lab11/M-ulator/blob/135867a92bb962b1e2df1d3d308f3a78211cf9aa/simulator/core/atomic_support.h#L15):
```C
# elif 0 // as of 3.4 clang BUG's at -O1+ with atomics
```
Should we bother with such a check anymore? Or a better question, how can we check if this is still a problem? clang is currently at version 11.0.0.

LIkely related, it appears latest clang supports C11 properly, including having stdatomic. Should we continue supporting such old versions of clang?

**Comment by ppannuto** [comment]
Goodness no! Let's bring this up to modern systems. I don't feel any obligation to support anything prior to clang v11.

That said; if the future is typescript, don't burn too much time with micro-optimizations*. Purging workarounds for long out-of-date compilers is totally valid however.

*advice I wish I had better followed when writing this -- there are a non-zero number of them in the code base

**Comment by gemarcano** [comment]
OK, sounds good. I'm mostly just finding things as I'm going around understanding the code base and beginning to add documentation.

I'll post a PR removing that ancient clang workaround.
